package com.furb.poo.provas.prova03.view;

import com.furb.poo.provas.prova03.model.Aluno;
import com.furb.poo.provas.prova03.model.AlunoController;
import com.furb.poo.provas.prova03.model.NotaInvalidaException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author André Felipe Bürger (afburger@furb.br)
 */
public class App extends javax.swing.JFrame {

    private AlunoController controller;
    private List<Aluno> alunos;
    private List<Double> notas;
    
    /**
     * Creates new form App
     */
    public App() {
        try {
            initComponents();
            controller = new AlunoController();
            
            alunos = controller.lerArquivo(controller.FILE_PATH);
            
            for (Aluno aluno : alunos) {
                taAlunos.append(aluno.toString());
                taAlunos.append("\n");
            }
            
        } catch (IOException | NumberFormatException ex) {
            alunos = new ArrayList<>();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAluno = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btIncluirNota = new javax.swing.JButton();
        btSalvarAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlunos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Aluno"));

        lbNome.setText("Nome:");

        btIncluirNota.setText("Incluir Nota");
        btIncluirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirNotaActionPerformed(evt);
            }
        });

        btSalvarAluno.setText("Salvar Aluno");
        btSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAlunoLayout = new javax.swing.GroupLayout(pnAluno);
        pnAluno.setLayout(pnAlunoLayout);
        pnAlunoLayout.setHorizontalGroup(
            pnAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIncluirNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnAlunoLayout.createSequentialGroup()
                        .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addComponent(btSalvarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnAlunoLayout.setVerticalGroup(
            pnAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btIncluirNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvarAluno)
                .addContainerGap())
        );

        taAlunos.setEditable(false);
        taAlunos.setColumns(20);
        taAlunos.setRows(5);
        taAlunos.setEnabled(false);
        jScrollPane1.setViewportView(taAlunos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(pnAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirNotaActionPerformed
        NotaView notaView = new NotaView(this, true);
        notaView.setVisible(true);
        
        if (notas == null) {
            notas = new ArrayList<>();
        }

        notas.add(notaView.getNota());
        
    }//GEN-LAST:event_btIncluirNotaActionPerformed

    private void btSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAlunoActionPerformed
        try {
            Double media = controller.calcularMedia(notas);
            Aluno aluno = new Aluno();
            aluno.setMedia(media);
            aluno.setNome(tfNome.getText());
            
            alunos.add(aluno);
            
            taAlunos.append(aluno.toString());
            taAlunos.append("\n");
            controller.salvarAlunos(alunos);
            
            tfNome.setText(null);
            notas = null;
        } catch (IOException | NotaInvalidaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btSalvarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluirNota;
    private javax.swing.JButton btSalvarAluno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JPanel pnAluno;
    private javax.swing.JTextArea taAlunos;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
